-- SQL Schema for Supabase
-- Run this query in your Supabase SQL Editor:

CREATE TABLE IF NOT EXISTS public.tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cookie TEXT NOT NULL,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Optional, or allow public access for anon key)
ALTER TABLE public.tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to tokens" ON public.tokens
    FOR ALL
    USING (true)
    WITH CHECK (true);
